// 5-148: 来自赵研老师的D:\WORK1\new_pangenome\accession_info\3rd_pan_out样本经纬度信息.xlsx
// 此文件中缺少的5个: 日本晴不算, 缺4个
// Nip_hifi
// W1952
// W2296
// W3101
// W3102
// W1952数据来自同路径野生稻TableS2.xlsx
// 剩下的3个没找着

const accessionInfo = [
  {
    name: 'W1952',
    newGroup: 'Or-III',
    newSubgroup: 'Or-III',
    originalProducingArea: '-',
    oriEcotype: '-',
    oriSubgroup: '-',
    originDataset: '?',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W2296',
    newGroup: 'O. rufipogon',
    newSubgroup: '-',
    originalProducingArea: '-',
    oriEcotype: '',
    oriSubgroup: '-',
    originDataset: '?',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W3101',
    newGroup: 'O. rufipogon',
    newSubgroup: '-',
    originalProducingArea: '-',
    oriEcotype: '-',
    oriSubgroup: '-',
    originDataset: '?',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W3102',
    newGroup: 'O. rufipogon',
    newSubgroup: '-',
    originalProducingArea: '-',
    oriEcotype: '-',
    oriSubgroup: '-',
    originDataset: '?',
    province: '-',
    originalLocation: '-'
  },
// zhaoyan start
  {
    name: 'GP100',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: '-',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'GP119',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: '-',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'GP622',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: '-',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W2099',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Australia',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Queensland, Australia '
  },
  {
    name: 'W2108',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Australia',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Queensland, Australia '
  },
  {
    name: 'W2064',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Bangladesh',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'KH-5 Khulna, Bangladesh '
  },
  {
    name: 'W2053',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Bangladesh',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'HS-6 Hobiganji, Bangladesh '
  },
  {
    name: 'W2051',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Bangladesh',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'HS-4 Hobiganji, Bangladesh '
  },
  {
    name: 'W1825',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Bangladesh',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Bangladesh '
  },
  {
    name: 'W3086',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '云南',
    originalLocation: '元江哈尼族彝族傣族自治县'
  },
  {
    name: 'W3088',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '云南',
    originalLocation: '元江哈尼族彝族傣族自治县'
  },
  {
    name: 'W3035',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '玉林'
  },
  {
    name: 'HP436',
    newGroup: 'Os.japonica',
    newSubgroup: '-',
    originalProducingArea: 'China',
    oriEcotype: 'Os.japonica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '湖南',
    originalLocation: '益阳县'
  },
  {
    name: 'HP519',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: 'China',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '湖南',
    originalLocation: '益阳县'
  },
  {
    name: 'W3071',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '海南',
    originalLocation: '文昌县'
  },
  {
    name: 'W3074',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '海南',
    originalLocation: '文昌县'
  },
  {
    name: 'W3054',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国内野生稻',
    province: '海南',
    originalLocation: '万宁县'
  },
  {
    name: 'W3055',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国内野生稻',
    province: '海南',
    originalLocation: '万宁县'
  },
  {
    name: 'W3047',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '田阳县'
  },
  {
    name: 'W3052',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '田阳县'
  },
  {
    name: 'W3000',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广东',
    originalLocation: '遂溪县'
  },
  {
    name: 'W3066',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '海南',
    originalLocation: '乐东黎族自治县'
  },
  {
    name: 'W3007',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广东',
    originalLocation: '开平县'
  },
  {
    name: 'W3090',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'China',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国内野生稻',
    province: '云南',
    originalLocation: '景洪县'
  },
  {
    name: 'W3096',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '湖南',
    originalLocation: '江永县'
  },
  {
    name: 'W3046',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '横县'
  },
  {
    name: 'W3029',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '合浦县'
  },
  {
    name: 'W3040',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '桂平县'
  },
  {
    name: 'W3038',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '贵县'
  },
  {
    name: 'W3037',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '贵县'
  },
  {
    name: 'W3012',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广东',
    originalLocation: '广州'
  },
  {
    name: 'W3009',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广东',
    originalLocation: '高明县'
  },
  {
    name: 'W3082',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '江西',
    originalLocation: '东乡县'
  },
  {
    name: 'W3063',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '海南',
    originalLocation: '东方黎族自治县'
  },
  {
    name: 'W3092',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '湖南',
    originalLocation: '茶陵县'
  },
  {
    name: 'W3033',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '博白县'
  },
  {
    name: 'W3051',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国内野生稻',
    province: '广西',
    originalLocation: '百色'
  },
  {
    name: 'W1718',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'China',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'China '
  },
  {
    name: 'W1719',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'China',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'China '
  },
  {
    name: 'W1723',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'China',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'China '
  },
  {
    name: 'W1839',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'China',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'China '
  },
  {
    name: '534M',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: 'China',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '广东',
    originalLocation: '-'
  },
  {
    name: 'Gla4',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: 'China',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '安徽；湖北；湖南；江苏；江西；上海；浙江',
    originalLocation: '-'
  },
  {
    name: 'W1943',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'China',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '-',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'GP680',
    newGroup: 'Os.japonica',
    newSubgroup: '-',
    originalProducingArea: 'Cuba',
    oriEcotype: 'Os.japonica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W1737',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-9 28km S of Jeypore, India '
  },
  {
    name: 'W1736',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'India',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-8 28km S of Jeypore, India '
  },
  {
    name: 'W1735',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-7 40km N of Jeypore, India '
  },
  {
    name: 'W1783',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-67 Shimoga Dist., Mysore, India '
  },
  {
    name: 'W1777',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-51 98km NE of Chandrapur, India '
  },
  {
    name: 'W1732',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-4 100km S of Berhampur, India '
  },
  {
    name: 'W1750',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-22 30km S of Pakhanjore, India '
  },
  {
    name: 'W1748',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-20 200km N of Jeypore, India '
  },
  {
    name: 'W1731',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-2 55km E of Cuttack for Konarak, India '
  },
  {
    name: 'W1742',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'India',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'WI-14 100km N of Jeypore, India '
  },
  {
    name: 'W0149',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Raipur, Madhya Pradesh, India '
  },
  {
    name: 'W0103',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Patna, Cuttack, Orissa, India '
  },
  {
    name: 'W0147',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Patna, Cuttack, Orissa, India '
  },
  {
    name: 'W0107',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Pahala, Orissa, India '
  },
  {
    name: 'W1080',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Near Bagdogra, Assam, India '
  },
  {
    name: 'W1084',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Near Bagdogra, Assam, India '
  },
  {
    name: 'W1107',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Kokilamukh, India '
  },
  {
    name: 'W1117',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Kokilamukh, India '
  },
  {
    name: 'W0135',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Kesavaram, Samalkot, Andhra, India '
  },
  {
    name: 'W1126',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'India',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Karimganj, India '
  },
  {
    name: 'W0136',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Kadiam, Andhra, India '
  },
  {
    name: 'W0137',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Kadiam, Andhra, India '
  },
  {
    name: 'W1666',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'JR-4 26.34 N, 89.03 E, India '
  },
  {
    name: 'W1668',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'JP-4 18.52 N, 82.46 E, Orissa, India ca.1,000m alt. '
  },
  {
    name: 'W0157',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'India',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Inside of Titabar Rice Expt. Stn., Assam, India '
  },
  {
    name: 'W1093',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'India',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Gauhati, Assam, India '
  },
  {
    name: 'W1142',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Cuttack, Orissa, India 3miles from CRRI '
  },
  {
    name: 'W0108',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'India',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Cuttack, Orissa, India '
  },
  {
    name: 'W1677',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'CT-4 20.29 N, 86.01 E, Orissa, India '
  },
  {
    name: 'W1679',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'India',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'CT-4 20.29 N, 86.01 E, Orissa, India '
  },
  {
    name: 'W0133',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Bicavole, Samalkot, Andhra, India '
  },
  {
    name: 'W2005',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'India',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: '15.35 N, 74.20 E, 200-500m alt., India '
  },
  {
    name: 'GP58',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: 'India',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W2022',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Indonesia',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'KL-3 Kalimantan, Indonesia '
  },
  {
    name: 'W2197',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Indonesia',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'KL-13 Kalimantan, Indonesia '
  },
  {
    name: 'W1976',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'Indonesia',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'IL-A Between Bogor and Jakarta, Indonesia '
  },
  {
    name: 'W1292',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Indonesia',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Handilmanarap, Kalimantan, Indonesia '
  },
  {
    name: 'W1970',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Indonesia',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: '(-a) IL-274, (-b) IL-281, (-c) Between Bogor and Jakarta, Indonesia '
  },
  {
    name: 'GP505',
    newGroup: 'Os.japonica',
    newSubgroup: '-',
    originalProducingArea: 'Japan',
    oriEcotype: 'Os.japonica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W2311',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Laos',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'LV9<br>17.52 N, 102.36 E, Vientian, Laos '
  },
  {
    name: 'W2310',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Laos',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'LV8<br>17.51 N, 102.36 E, Vientian, Laos '
  },
  {
    name: 'W2308',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Laos',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'LV1<br>17.57 N, 102.38 E, Vientian, Laos '
  },
  {
    name: 'W2305',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Laos',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'LP9a<br>14.50 N, 105.50 E, Ban Nong Sa, Phakse, Laos '
  },
  {
    name: 'W2267',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Laos',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: ' 18.14 N, 102.42 E, Laos '
  },
  {
    name: 'W0600',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Malaysia',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Padang Kemunting, Malaya '
  },
  {
    name: 'W0594',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Malaysia',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Malaya '
  },
  {
    name: 'W0596',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Malaysia',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Malaya '
  },
  {
    name: 'W0590',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Malaysia',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Jerteh, Malaya '
  },
  {
    name: 'W0573',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'Malaysia',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Bachak (Kelantan), Malaya '
  },
  {
    name: 'W0632',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Myanmar',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Pyin-ma-aing, Prome, Burma '
  },
  {
    name: 'W2036',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Myanmar',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Pegu, Burma '
  },
  {
    name: 'W0634',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Myanmar',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Myitkyina, Burma '
  },
  {
    name: 'W0630',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Myanmar',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Magwe, Burma '
  },
  {
    name: 'W0639',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Myanmar',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Burma '
  },
  {
    name: 'W0627',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Myanmar',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'between Pedu and Toungoo (?), Burma '
  },
  {
    name: 'W2066',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Nepal',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Surkhet, Nepal '
  },
  {
    name: 'GP635',
    newGroup: 'Os.intermedia',
    newSubgroup: '-',
    originalProducingArea: 'North Korea',
    oriEcotype: 'Os.intermedia',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W1236',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Papua New Guinea',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Madang, Australian New Guinea '
  },
  {
    name: 'W1214',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Philippines',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Musuan, Mindanao, Philippines '
  },
  {
    name: 'GP524',
    newGroup: 'Os.indica',
    newSubgroup: '-',
    originalProducingArea: 'Philippines',
    oriEcotype: 'Os.indica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'GP523',
    newGroup: 'Os.japonica',
    newSubgroup: '-',
    originalProducingArea: 'Solomon Islands',
    oriEcotype: 'Os.japonica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W1809',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'Srilanka',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Sri Lanka '
  },
  {
    name: 'W1810',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Srilanka',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Sri Lanka '
  },
  {
    name: 'W1536',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIA',
    originalProducingArea: 'Srilanka',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIb',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Putlalam (?), Ceylon '
  },
  {
    name: 'W0143',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Srilanka',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Negombo, Ceylon '
  },
  {
    name: 'W1787',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Thailand '
  },
  {
    name: 'W1619',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'SRB Saraburi, Thailand '
  },
  {
    name: 'W1557',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'SPB Suphanburi, Thailand '
  },
  {
    name: 'W1547',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Saraburi, Thailand '
  },
  {
    name: 'W0179',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Rajburi, Thailand '
  },
  {
    name: 'W0234',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Nongkai, Thailand '
  },
  {
    name: 'W2283',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'NN59b 16.49 N, 99.47 E, Thailand '
  },
  {
    name: 'W1859',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'NN51 17.52 N, 100.12 E, Thailand 70m alt. '
  },
  {
    name: 'W0180',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Ngao, Lamphang, Thailand '
  },
  {
    name: 'W1919',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'NE85 14.73 N, 102.19 E, Thailand ca.150m alt. '
  },
  {
    name: 'W1895',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'NE47 17.25 N, 104.18 E, Thailand 180m alt. '
  },
  {
    name: 'W1890',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'NE37 17.85 N, 102.75 E, Thailand 170m alt. '
  },
  {
    name: 'W1865',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'NE3 14.56 N, 100.98 E, Thailand 20m alt. '
  },
  {
    name: 'W1880',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'NE25 17.03 N, 102.91 E, Thailand 210m alt. '
  },
  {
    name: 'W1553',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'MRT Maharat, Thailand '
  },
  {
    name: 'W1550',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'CR-6 Phan, Chiangrai, Thailand '
  },
  {
    name: 'W2275',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'CP41 16.09 N, 100.37 E, Thailand '
  },
  {
    name: 'W0169',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Chumpae, Konkhen, Thailand '
  },
  {
    name: 'W0171',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Chumpae, Konkhen, Thailand '
  },
  {
    name: 'W0164',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Chiengmai, Thailand '
  },
  {
    name: 'W0166',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Chiengmai, Thailand '
  },
  {
    name: 'W1559',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIC',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'BNB Bahn Non Bo, Thailand '
  },
  {
    name: 'W0145',
    newGroup: 'Non-Specific',
    newSubgroup: 'Non-Specific',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'Bangkok,Thailand '
  },
  {
    name: 'W1726',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'B Thailand '
  },
  {
    name: 'W1552',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'AYD Ayutthaya, Thailand '
  },
  {
    name: 'W1556',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'ATS Between Anthong and Suphanburi, Thailand '
  },
  {
    name: 'W1725',
    newGroup: 'Or-III',
    newSubgroup: 'Or-IIIB',
    originalProducingArea: 'Thailand',
    oriEcotype: 'Or-III',
    oriSubgroup: 'Or-IIIa',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'A Thailand '
  },
  {
    name: 'GP543',
    newGroup: 'Os.intermedia',
    newSubgroup: '-',
    originalProducingArea: 'United States',
    oriEcotype: 'Os.intermedia',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'GP117',
    newGroup: 'Os.japonica',
    newSubgroup: '-',
    originalProducingArea: 'United States',
    oriEcotype: 'Os.japonica',
    oriSubgroup: '-',
    originDataset: 'cultivated',
    province: '-',
    originalLocation: '-'
  },
  {
    name: 'W2319',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Vietnam',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'HT17<br>10.33 N, 106.25 E, Long An Prov., Vietnam '
  },
  {
    name: 'W2318',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Vietnam',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'HT16<br>10.24 N, 106.06 E, Tieng Giang Prov., Vietnam '
  },
  {
    name: 'W2321',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Vietnam',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'CT3<br>10.44 N, 105.37 E, Tan Cong Sinh vil., Vietnam '
  },
  {
    name: 'W2332',
    newGroup: 'Or-I',
    newSubgroup: 'Or-I',
    originalProducingArea: 'Vietnam',
    oriEcotype: 'Or-I',
    oriSubgroup: 'Or-I',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'CT17<br>Vietnam '
  },
  {
    name: 'W2320',
    newGroup: 'Or-II',
    newSubgroup: 'Or-II',
    originalProducingArea: 'Vietnam',
    oriEcotype: 'Or-II',
    oriSubgroup: 'Or-II',
    originDataset: '国外野生稻',
    province: '-',
    originalLocation: 'CT1<br>10.42 N, 105.36 E, Vetnam '
  }
]
export default accessionInfo
