import React, { useState } from 'react'
import { Form, Input, Checkbox, Select, Button, message, Upload, Divider, Space, Col, Row } from 'antd'
import { InboxOutlined } from '@ant-design/icons';
import PubSub from 'pubsub-js'
import { request } from '../../components/Request'
import options from '../ExpressMatrix/options'
const { Dragger } = Upload;
// import options from './options'

// TCAGCTGGCCGCCTCGACCTGCGCCGTCGCGGCGGCGTCGGCGGCCGGCGGCGCGAGCCAGCGCGTGAAGGCGTCGAGCGTGCGGGTGTCGGCGCGGTAGTGGCGCTGCGTGAAGCGCATGAGGTCGGCCCAGGTGAAGTCCGGGTAGTGCCGCGGCGTGGCGGCGCTCGGCGGCGGCCGCACCACCCTGTCCTCCCGCGGGCACAGGAAGAACGCCAGCGACCGCCGCTCCCGCCGCTGGTTCACCACCGCCCTGTGCAGGCAGCTCTTATACCTCCCGTTCGACAGCGCCTGCACACACAACAATTCCCCACAAATTCCTTCAGACAAAAAAAAATACATACATACATCATCATTCATCAACGGAGAGGCCGACACGTGCAGGGCTACATCGCCAATGTCCGTGCCCCCGTCGCCGGCTGAGCAACGCGACAAGGACAAACCGCGCGAGAGAGGCGCACGACGCGACAAGAGCCGCGGCGAGGGTGGCGCCAAATCGATCGGCATGGAACAATCCGCGCCCGCGCGCGGAACACACCACCCTAAGCTACCGTCCGCCCGCGGCGACGACGACGTACGTGCGTGCGCGCGCGTGTGTGTGGCGTGCAGCCGCACGCCGCGCCATGCCATCCCCCCCAAGCGCCAAACCAAAACCCCCCCGGGAAAACGCCACCGAAAGCGCCACCATCCGCATCCGTCCCCGCGGCGCCGCTGCTACTACTACACAAATCCCTCCAAAATACACATCCAACGAGGAGGAGAACGCATGCTTATCTCTCATCTCTCCTCTTCTCTACTCTTCCATAATCCATATCTTGGCTTGGCATGGCATGACCGAGTCTGGTCCTTCCAAGTGCCATGGATGGATAGGAGCAGGGCCTGTTTATCCTAATTTTGTTTTCTTTTAAAATGTATACTGTTATAGTATTATATAGGAAATTAACTATAACAAACAGGTTTATATACGGATGATGAAATTATCCGCTTTCATCGTTAGATAGGAGTTAGGGCTAGAGATGGAAGTGACTGGCGAGAATGGACACAAATGTATGTGCTCGTGTGCAAGTTGGTGGTGGCTAACTCAACTCACACTTTGTTTGTCATCAAATACTAAAACGCGACGAGACACTACTCACTACTGTTTGGAGTGTTAGGGGGGGACCCAGGGGTTGTTGGACGTGGCTGTTGGCACCTCTGGCCGTCCAGGCCCACCGAAGCTTACATGGCGTCGTCACACCATCGGAAAATATTCGCATGTCGGGGGAGATCCATATTAATTACTCCTTCCATTTTATCTTATAAATGGCTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTAGCTTGTTACTTACTCCTATTAACTATAAGATGTGAGATAAATCATAACACATGGAGGAGTGGGGCATTCCATTGTTTGTGATTGGAACAGAGAAATCACGTCAGATCGGTTTCTTCCCGCTTTCAGCTGAAAGCCCCGCCCCTACCACGATCTTATTTTTCTCGTCAATTTCGCGCGAGAGAGAAAAAAAAGCTTGAATTACTTGTTCTGTTGCTTCGAAGCAGAGGAGAACAGAGGAGAGGAGAATAGGAGATGGTTTACCATGAAGGTGTCGCCGATGTTGATGACCATGGCGCCGGGGACGGGGCTGACGGGGCGCCATTCGCCGTCGACGAGGACCTCGAGGCCGCCGACGTCGTCCTGGAGGAGGATGGTGAGGGCGGTGGGGTCGCAGTGCGGGCCCGTGCCGAGCGTCCGCTCCGGCTCCGGGCATGGCGGGTAGTAGTTGCACCGCATGATTGAGCTGCTGTCCGCGAAGAACTCCCTGTAGTAGCCTCGCTCCACGCCCAGGCTCAGCTCCAGGAGTTCCATGATCGTCAGCGACAGCTCCTTCATCTCCTCGCAGTACTTCTGGTACACCCTCCTGCGCGCACAAACGCGTTTGAATTCAGCATAATCTCGGTCGGTGTGTTTTGAATTTGTTTTGAATTTGAAATGCAATGTCGTCCACCATCGTTTTAATTACCCCATTGGCGCGAAGTCGGGGCCGAGGGTGCTGGAGAAGTAGTCGGCGACGACGGGGGCGGCGGCGCGGTCGTGGAAGCCGAAGGAGAGGGTCTCCTTCCATGGGAGCTTGGAGGCGAAGCGGTCGGCGTGGGCGCTGGTGTAGCCGGACACGGTGCCCGGGACGCGGCGCGCGCGGCGCTTCTCGGCGAGCGGGAGGCGGAAGAAGTCGCTGGCGCCGTCGAGCGCGGCGCGCGCCAGAGCGGCGTCGACGCCGTGCCCGGACACCTGGAAGAACCCGTGCGTGGCGCACGCGGCGGCCACCTGCGCCGCGGCGCGGCGCAGCCCCTCGGCGTCGCCGTCGCGGAGCACGCCCACGTCGACCACGGGCATGTCCAGCTCCGCCGCCGACGCCGGCCTCGCGTCGCCGTTCGGCCACACGAATGGCTCCGGGATCTTGGGCTCCATCCTCAGGTCGCACACCGCCGCCGCCGCCGGGGCGGCAATGCCAGAGCCGGCGGTGGAGTCCATGGGCGGTGGTTGGTGCGGCTGTGGTGGCGTGGGGTGCTCGGCCACCATGAGATTGGAGATGAGAAGTGAGCGCTGTGTTGAGCGGGAGTGAGTTGAGAGCGTGTGTGAGTGTGAGTGTGTGTGTGTGTGCAGGGCGAGCTGTCTGGGCAGGAGGGTGGGGTATTTGTAACAGGGGAGAAGACGAGCGCCAT

const { TextArea } = Input

// 上传文件需要的
const props = {
  name: 'file',
  multiple: true,
  action: 'https://www.mocky.io/v2/5cc8019d300000980a055e76',
  onChange(info) {
    const { status } = info.file;
    if (status !== 'uploading') {
      console.log(info.file, info.fileList);
    }
    if (status === 'done') {
      message.success(`${info.file.name} file uploaded successfully.`);
    } else if (status === 'error') {
      message.error(`${info.file.name} file upload failed.`);
    }
  },
  onDrop(e) {
    console.log('Dropped files', e.dataTransfer.files);
  },
};

export default function FormHeatmap(msg) {

  const { url, pubName } = msg

  // 表单的回调
  const onFinish = (values) => {
    console.log('heatmap Success:', values);
    if (values){
      request.get(url, {params: {values}}).then((result)=>{
        if(result.status === 200){
          PubSub.publish(pubName, result.data)
        }
      })
      
    } else if (!values) {
      console.log('input cant be empty');
    }
  }

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo)
  }

  // 表单样式
  const formItemLayout = {
    labelCol: {
      span: 6,
    },
    wrapperCol: {
      span: 14,
    },
  };

  // accessions选择的回调
  const handleChange = (value) => {
    console.log(`selected ${value}`);
  };

  return (
      <>
        <Divider></Divider>
        <Row>
          <Col offset={3}>
          </Col>
          <Form
            name='blat'
            initialValues={{
              remember: true,
              variations: ['W1943', "W2064", 'GP100'],
              // variations: ['W1943'],
              geneSet: ["TCAGCTGGCCGCCTCGACCTGCGCCGTCGCGGCGGCGTCGGCGGCCGGCGGCGCGAGCCAGCGCGTGAAGGCGTCGAGCGTGCGGGTGTCGGCGCGGTAGTGGCGCTGCGTGAAGCGCATGAGGTCGGCCCAGGTGAAGTCCGGGTAGTGCCGCGGCGTGGCGGCGCTCGGCGGCGGCCGCACCACCCTGTCCTCCCGCGGGCACAGGAAGAACGCCAGCGACCGCCGCTCCCGCCGCTGGTTCACCACCGCCCTGTGCAGGCAGCTCTTATACCTCCCGTTCGACAGCGCCTGCACACACAACAATTCCCCACAAATTCCTTCAGACAAAAAAAAATACATACATACATCATCATTCATCAACGGAGAGGCCGACACGTGCAGGGCTACATCGCCAATGTCCGTGCCCCCGTCGCCGGCTGAGCAACGCGACAAGGACAAACCGCGCGAGAGAGGCGCACGACGCGACAAGAGCCGCGGCGAGGGTGGCGCCAAATCGATCGGCATGGAACAATCCGCGCCCGCGCGCGGAACACACCACCCTAAGCTACCGTCCGCCCGCGGCGACGACGACGTACGTGCGTGCGCGCGCGTGTGTGTGGCGTGCAGCCGCACGCCGCGCCATGCCATCCCCCCCAAGCGCCAAACCAAAACCCCCCCGGGAAAACGCCACCGAAAGCGCCACCATCCGCATCCGTCCCCGCGGCGCCGCTGCTACTACTACACAAATCCCTCCAAAATACACATCCAACGAGGAGGAGAACGCATGCTTATCTCTCATCTCTCCTCTTCTCTACTCTTCCATAATCCATATCTTGGCTTGGCATGGCATGACCGAGTCTGGTCCTTCCAAGTGCCATGGATGGATAGGAGCAGGGCCTGTTTATCCTAATTTTGTTTTCTTTTAAAATGTATACTGTTATAGTATTATATAGGAAATTAACTATAACAAACAGGTTTATATACGGATGATGAAATTATCCGCTTTCATCGTTAGATAGGAGTTAGGGCTAGAGATGGAAGTGACTGGCGAGAATGGACACAAATGTATGTGCTCGTGTGCAAGTTGGTGGTGGCTAACTCAACTCACACTTTGTTTGTCATCAAATACTAAAACGCGACGAGACACTACTCACTACTGTTTGGAGTGTTAGGGGGGGACCCAGGGGTTGTTGGACGTGGCTGTTGGCACCTCTGGCCGTCCAGGCCCACCGAAGCTTACATGGCGTCGTCACACCATCGGAAAATATTCGCATGTCGGGGGAGATCCATATTAATTACTCCTTCCATTTTATCTTATAAATGGCTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTAGCTTGTTACTTACTCCTATTAACTATAAGATGTGAGATAAATCATAACACATGGAGGAGTGGGGCATTCCATTGTTTGTGATTGGAACAGAGAAATCACGTCAGATCGGTTTCTTCCCGCTTTCAGCTGAAAGCCCCGCCCCTACCACGATCTTATTTTTCTCGTCAATTTCGCGCGAGAGAGAAAAAAAAGCTTGAATTACTTGTTCTGTTGCTTCGAAGCAGAGGAGAACAGAGGAGAGGAGAATAGGAGATGGTTTACCATGAAGGTGTCGCCGATGTTGATGACCATGGCGCCGGGGACGGGGCTGACGGGGCGCCATTCGCCGTCGACGAGGACCTCGAGGCCGCCGACGTCGTCCTGGAGGAGGATGGTGAGGGCGGTGGGGTCGCAGTGCGGGCCCGTGCCGAGCGTCCGCTCCGGCTCCGGGCATGGCGGGTAGTAGTTGCACCGCATGATTGAGCTGCTGTCCGCGAAGAACTCCCTGTAGTAGCCTCGCTCCACGCCCAGGCTCAGCTCCAGGAGTTCCATGATCGTCAGCGACAGCTCCTTCATCTCCTCGCAGTACTTCTGGTACACCCTCCTGCGCGCACAAACGCGTTTGAATTCAGCATAATCTCGGTCGGTGTGTTTTGAATTTGTTTTGAATTTGAAATGCAATGTCGTCCACCATCGTTTTAATTACCCCATTGGCGCGAAGTCGGGGCCGAGGGTGCTGGAGAAGTAGTCGGCGACGACGGGGGCGGCGGCGCGGTCGTGGAAGCCGAAGGAGAGGGTCTCCTTCCATGGGAGCTTGGAGGCGAAGCGGTCGGCGTGGGCGCTGGTGTAGCCGGACACGGTGCCCGGGACGCGGCGCGCGCGGCGCTTCTCGGCGAGCGGGAGGCGGAAGAAGTCGCTGGCGCCGTCGAGCGCGGCGCGCGCCAGAGCGGCGTCGACGCCGTGCCCGGACACCTGGAAGAACCCGTGCGTGGCGCACGCGGCGGCCACCTGCGCCGCGGCGCGGCGCAGCCCCTCGGCGTCGCCGTCGCGGAGCACGCCCACGTCGACCACGGGCATGTCCAGCTCCGCCGCCGACGCCGGCCTCGCGTCGCCGTTCGGCCACACGAATGGCTCCGGGATCTTGGGCTCCATCCTCAGGTCGCACACCGCCGCCGCCGCCGGGGCGGCAATGCCAGAGCCGGCGGTGGAGTCCATGGGCGGTGGTTGGTGCGGCTGTGGTGGCGTGGGGTGCTCGGCCACCATGAGATTGGAGATGAGAAGTGAGCGCTGTGTTGAGCGGGAGTGAGTTGAGAGCGTGTGTGAGTGTGAGTGTGTGTGTGTGTGCAGGGCGAGCTGTCTGGGCAGGAGGGTGGGGTATTTGTAACAGGGGAGAAGACGAGCGCCAT"
            ]
            }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
            {...formItemLayout}
          >

          {/* 
            blat表单内容
            一个文本框 一个上传框
            一个database type
            一个query type
            一个选择比对的accessions的下拉框
            一个选择输出的文件格式的下拉框

          */}


            <Form.Item
              label="input your sequence:"
              name="inputSeq"
              rules={[
                {
                  required: true,
                  message: 'Please input a sequence!',
                },
              ]}
            >
              <TextArea 
                allowClear 
                maxLength={2000} 
                style={{width:'800px', height:'300px'}}
                // initialvalue={"TCAGCTGGCCGCCTCGACCTGCGCCGTCGCGGCGGCGTCGGCGGCCGGCGGCGCGAGCCAGCGCGTGAAGGCGTCGAGCGTGCGGGTGTCGGCGCGGTAGTGGCGCTGCGTGAAGCGCATGAGGTCGGCCCAGGTGAAGTCCGGGTAGTGCCGCGGCGTGGCGGCGCTCGGCGGCGGCCGCACCACCCTGTCCTCCCGCGGGCACAGGAAGAACGCCAGCGACCGCCGCTCCCGCCGCTGGTTCACCACCGCCCTGTGCAGGCAGCTCTTATACCTCCCGTTCGACAGCGCCTGCACACACAACAATTCCCCACAAATTCCTTCAGACAAAAAAAAATACATACATACATCATCATTCATCAACGGAGAGGCCGACACGTGCAGGGCTACATCGCCAATGTCCGTGCCCCCGTCGCCGGCTGAGCAACGCGACAAGGACAAACCGCGCGAGAGAGGCGCACGACGCGACAAGAGCCGCGGCGAGGGTGGCGCCAAATCGATCGGCATGGAACAATCCGCGCCCGCGCGCGGAACACACCACCCTAAGCTACCGTCCGCCCGCGGCGACGACGACGTACGTGCGTGCGCGCGCGTGTGTGTGGCGTGCAGCCGCACGCCGCGCCATGCCATCCCCCCCAAGCGCCAAACCAAAACCCCCCCGGGAAAACGCCACCGAAAGCGCCACCATCCGCATCCGTCCCCGCGGCGCCGCTGCTACTACTACACAAATCCCTCCAAAATACACATCCAACGAGGAGGAGAACGCATGCTTATCTCTCATCTCTCCTCTTCTCTACTCTTCCATAATCCATATCTTGGCTTGGCATGGCATGACCGAGTCTGGTCCTTCCAAGTGCCATGGATGGATAGGAGCAGGGCCTGTTTATCCTAATTTTGTTTTCTTTTAAAATGTATACTGTTATAGTATTATATAGGAAATTAACTATAACAAACAGGTTTATATACGGATGATGAAATTATCCGCTTTCATCGTTAGATAGGAGTTAGGGCTAGAGATGGAAGTGACTGGCGAGAATGGACACAAATGTATGTGCTCGTGTGCAAGTTGGTGGTGGCTAACTCAACTCACACTTTGTTTGTCATCAAATACTAAAACGCGACGAGACACTACTCACTACTGTTTGGAGTGTTAGGGGGGGACCCAGGGGTTGTTGGACGTGGCTGTTGGCACCTCTGGCCGTCCAGGCCCACCGAAGCTTACATGGCGTCGTCACACCATCGGAAAATATTCGCATGTCGGGGGAGATCCATATTAATTACTCCTTCCATTTTATCTTATAAATGGCTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTAGCTTGTTACTTACTCCTATTAACTATAAGATGTGAGATAAATCATAACACATGGAGGAGTGGGGCATTCCATTGTTTGTGATTGGAACAGAGAAATCACGTCAGATCGGTTTCTTCCCGCTTTCAGCTGAAAGCCCCGCCCCTACCACGATCTTATTTTTCTCGTCAATTTCGCGCGAGAGAGAAAAAAAAGCTTGAATTACTTGTTCTGTTGCTTCGAAGCAGAGGAGAACAGAGGAGAGGAGAATAGGAGATGGTTTACCATGAAGGTGTCGCCGATGTTGATGACCATGGCGCCGGGGACGGGGCTGACGGGGCGCCATTCGCCGTCGACGAGGACCTCGAGGCCGCCGACGTCGTCCTGGAGGAGGATGGTGAGGGCGGTGGGGTCGCAGTGCGGGCCCGTGCCGAGCGTCCGCTCCGGCTCCGGGCATGGCGGGTAGTAGTTGCACCGCATGATTGAGCTGCTGTCCGCGAAGAACTCCCTGTAGTAGCCTCGCTCCACGCCCAGGCTCAGCTCCAGGAGTTCCATGATCGTCAGCGACAGCTCCTTCATCTCCTCGCAGTACTTCTGGTACACCCTCCTGCGCGCACAAACGCGTTTGAATTCAGCATAATCTCGGTCGGTGTGTTTTGAATTTGTTTTGAATTTGAAATGCAATGTCGTCCACCATCGTTTTAATTACCCCATTGGCGCGAAGTCGGGGCCGAGGGTGCTGGAGAAGTAGTCGGCGACGACGGGGGCGGCGGCGCGGTCGTGGAAGCCGAAGGAGAGGGTCTCCTTCCATGGGAGCTTGGAGGCGAAGCGGTCGGCGTGGGCGCTGGTGTAGCCGGACACGGTGCCCGGGACGCGGCGCGCGCGGCGCTTCTCGGCGAGCGGGAGGCGGAAGAAGTCGCTGGCGCCGTCGAGCGCGGCGCGCGCCAGAGCGGCGTCGACGCCGTGCCCGGACACCTGGAAGAACCCGTGCGTGGCGCACGCGGCGGCCACCTGCGCCGCGGCGCGGCGCAGCCCCTCGGCGTCGCCGTCGCGGAGCACGCCCACGTCGACCACGGGCATGTCCAGCTCCGCCGCCGACGCCGGCCTCGCGTCGCCGTTCGGCCACACGAATGGCTCCGGGATCTTGGGCTCCATCCTCAGGTCGCACACCGCCGCCGCCGCCGGGGCGGCAATGCCAGAGCCGGCGGTGGAGTCCATGGGCGGTGGTTGGTGCGGCTGTGGTGGCGTGGGGTGCTCGGCCACCATGAGATTGGAGATGAGAAGTGAGCGCTGTGTTGAGCGGGAGTGAGTTGAGAGCGTGTGTGAGTGTGAGTGTGTGTGTGTGTGCAGGGCGAGCTGTCTGGGCAGGAGGGTGGGGTATTTGTAACAGGGGAGAAGACGAGCGCCAT"}
              >
              </TextArea>
            </Form.Item>

            
            <Form.Item
              label="or upload your sequence file:"
              name="uploadSeq"
              valuePropName="fileList"
            >
              <Dragger {...props}>
                <p className="ant-upload-drag-icon">
                  <InboxOutlined />
                </p>
                <p className="ant-upload-text">Click or drag file to this area to upload</p>
                <p className="ant-upload-hint">
                  Support for a single or bulk upload. Strictly prohibited from uploading company data or other
                  banned files.
                </p>
              </Dragger>
            </Form.Item>


            {/* ........... 
              选择品种
            */}
            <Form.Item name="accession" label="accession"
              rules={[
                {
                  required: true,
                  message: '!',
                },
              ]}
              onChange={(value)=>{console.log('form item of abc:', value.currentTarget)}}
            >
              <Select
                allowClear
                style={{
                  width: '100%',
                }}
                placeholder="Please select"
                onChange={handleChange}
                options={options}
              />
            </Form.Item>
            {/* ........... */}


            {/* ........... 
              query type
                dna - DNA sequence
                rna - RNA sequence
                prot - protein sequence
                dnax - DNA sequence translated in six frames to protein
                rnax - DNA sequence translated in three frames to protein
            */}
            <Form.Item name="queryStyle" label="query style"
              rules={[
                {
                  required: true,
                  message: '!',
                },
              ]}
              onChange={(value)=>{console.log('form item of abc:', value.currentTarget)}}
            >
              <Select
                mode=""
                allowClear
                style={{
                  width: '100%',
                }}
                placeholder="Please select"
                onChange={handleChange}
                options={[{label: 'DNA',
                          value: 'dna'},
                          {label: 'RNA',
                          value: 'rna'},{
                          label: 'Protein',
                          value: 'prot'},{ 
                          label: 'DNA translated in six frames to protein',
                          value: 'dnax'},{ 
                          label: 'DNA translated in three frames to protein',
                          value: 'rnax'}]}
              />
            </Form.Item>
            {/* ........... */}


            

            <Form.Item
              wrapperCol={{
                offset: 8,
                span: 16,
              }}
            >
              <Button type="primary" htmlType="submit">
                Submit
              </Button>
            </Form.Item>

          </Form>

        </Row>
        <Divider></Divider>
      </>
  )
}

// p = '149_CDS_pa/(.*)[\.all]{0,1}?\.evm\.out_nucleus\.cds'
// l = []
// for i in s:
//     st = re.findall(p, i)[0]
//     st = st.replace('.all', '')
//     l.append(st)
